-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "date" SET DATA TYPE DATE,
ALTER COLUMN "createdAt" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "Income" ALTER COLUMN "date" SET DATA TYPE DATE,
ALTER COLUMN "createdAt" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "today" SET DATA TYPE DATE;
